'use strict';
(() => {
const $ = (s) => document.querySelector(s);
const esc = (v = '') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {home:'M3 11 12 3l9 8M5 10v11h5v-7h4v7h5V10',tasks:'M9 5h12M9 12h12M9 19h12M2 5l2 2 3-4M2 12l2 2 3-4M2 19l2 2 3-4',calendar:'M4 5h16v16H4zM4 10h16M8 3v4M16 3v4',habit:'M12 3c0 6-8 7-8 13a8 8 0 0 0 16 0c0-3-2-6-4-8 0 4-4 5-4 5s2-5 0-10Z',food:'M5 3v7M2 3v5a3 3 0 0 0 6 0V3M5 11v10M18 3c-4 3-4 9 0 9V3Zm0 9v9',book:'M12 5v16M12 5C8 2 3 3 3 3v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2Z',settings:'M9 3h6l1 4 4 1 1 5-3 3v4l-5 1-3-3-4 1-3-4 2-4-1-4 5-1Zm3 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6',plus:'M12 5v14M5 12h14',minus:'M5 12h14',check:'m5 12 4 4L19 6',close:'m6 6 12 12M6 18 18 6',edit:'m14 5 5 5M4 20l5-1L21 7l-5-5L4 14v6Z',trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',water:'M12 2c-3 5-8 9-8 13a8 8 0 0 0 16 0c0-4-5-8-8-13Z',glass:'M5 3h14l-2 18H7L5 3ZM6 9h12',sun:'M12 2v2M12 20v2M2 12h2M20 12h2M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2M16 12a4 4 0 1 0-8 0 4 4 0 0 0 8 0',clock:'M12 8v5l3 2M21 12a9 9 0 1 0-18 0 9 9 0 0 0 18 0',left:'m14 6-6 6 6 6',right:'m10 6 6 6-6 6',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',cloud:'M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13-1 5 5 0 0 1 0 11H6',leaf:'M20 3C7 2 1 9 5 16c7 7 15 0 15-13ZM5 20 16 8'};
const icon = (name, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.home}"/></svg>`;
const uid = () => crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2);
const dateKey = (d = new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseDate = s => new Date(`${s}T12:00:00`);
const shift = (d,n) => { const result = new Date(d); result.setDate(result.getDate()+n); return result; };
const today = () => dateKey();
const fmtDate = (s,opts={day:'numeric',month:'short'}) => parseDate(s).toLocaleDateString('pt-BR',opts);
const startWeek = d => shift(d,-((d.getDay()+6)%7));
const navs = [['inicio','home','Hoje'],['tarefas','tasks','Tarefas'],['agenda','calendar','Agenda'],['habitos','habit','Hábitos'],['alimentacao','food','Alimentação'],['conteudos','book','Leituras']];
const emptyState = () => ({schemaVersion:1,name:'',tasks:[],events:[],habits:[],meals:{},water:{},waterGoal:8});
const demoState = () => ({...emptyState(),tasks:[{id:uid(),title:'Planejar as prioridades da semana',date:today(),priority:'alta',category:'Pessoal',done:false},{id:uid(),title:'Ler 20 páginas do meu livro',date:today(),priority:'media',category:'Desenvolvimento',done:false},{id:uid(),title:'Separar um tempo para me movimentar',date:today(),priority:'baixa',category:'Bem-estar',done:false},{id:uid(),title:'Organizar meu espaço de trabalho',date:today(),priority:'media',category:'Pessoal',done:true}],events:[{id:uid(),title:'Tempo para aprender',date:today(),start:'09:00',end:'10:00',category:'Desenvolvimento',color:'green',notes:''},{id:uid(),title:'Pausa para o almoço',date:today(),start:'12:00',end:'13:00',category:'Bem-estar',color:'orange',notes:''},{id:uid(),title:'Caminhada ao ar livre',date:today(),start:'17:30',end:'18:00',category:'Pessoal',color:'purple',notes:''}],habits:[{id:uid(),title:'Ler um pouco todos os dias',goal:'20 minutos de leitura',icon:'book',days:[]},{id:uid(),title:'Reservar um momento para mim',goal:'Uma pausa sem telas',icon:'sun',days:[today()]},{id:uid(),title:'Movimentar o corpo',goal:'No meu tempo, do meu jeito',icon:'leaf',days:[]}],water:{[today()]:3}});
let state = demoState(), route = '', taskFilter='todas', search='', blogFilter='Todos', calendarDate=new Date(), calendarView='mes', selectedDay=today(), mealDate=today(), revision=0, syncBusy=false, loaded=false, operationBusy=false;
const articles = [
 {id:1,category:'Alimentação',title:'Comer bem começa com escolhas possíveis',summary:'Conheça o Guia Alimentar brasileiro e suas orientações sobre alimentos, preparo e organização das refeições.',source:'Ministério da Saúde',lang:'Português',url:'https://www.gov.br/saude/pt-br/composicao/saps/promocao-da-saude/guias-alimentares',body:'O Guia Alimentar para a População Brasileira é uma referência pública para pensar a alimentação no dia a dia. Ele também considera os obstáculos para colocar as orientações em prática, como tempo, custo e habilidades culinárias.\n\nPara começar a organizar sua rotina, use o planejador para registrar as refeições que pretende preparar e consulte a fonte para conhecer as recomendações completas. Esse planejamento é pessoal e não calcula uma dieta ou prescrição nutricional.'},
 {id:2,category:'Bem-estar',title:'Uma rotina que também abre espaço para descansar',summary:'Uma seleção de orientações do NHS para compreender o sono e construir uma rotina de descanso.',source:'NHS · Every Mind Matters',lang:'Inglês',url:'https://www.nhs.uk/every-mind-matters/mental-health-issues/sleep/',body:'O NHS reúne informações sobre sono e orientações para quem encontra dificuldades para descansar. A página apresenta recursos para entender o tema e buscar apoio.\n\nNo seu planejamento, você pode reservar um horário para desacelerar e registrar um hábito de descanso. Leia o conteúdo original, em inglês, para conhecer as orientações completas.'},
 {id:3,category:'Organização',title:'Seu tempo merece prioridades mais claras',summary:'Explore uma introdução à gestão do tempo e reflita sobre como organizar suas atividades e objetivos.',source:'Coursera',lang:'Inglês',url:'https://www.coursera.org/articles/time-management',body:'O artigo da Coursera apresenta a gestão do tempo e a relação entre objetivos, prioridades e acompanhamento do planejamento.\n\nUma forma de experimentar o tema no Ritmo é listar suas tarefas, escolher uma prioridade para cada uma e reservar horários na agenda. Revise o plano quando sua disponibilidade mudar.'},
 {id:4,category:'Bem-estar',title:'Pequenos cuidados com o seu bem-estar',summary:'Encontre recursos do NHS sobre saúde mental, autocuidado e bem-estar no cotidiano.',source:'NHS · Every Mind Matters',lang:'Inglês',url:'https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/',body:'O projeto Every Mind Matters reúne orientações e recursos sobre bem-estar mental. Você pode consultar os materiais e escolher um cuidado que faça sentido para sua rotina.\n\nO acompanhamento de hábitos funciona aqui como um registro pessoal, sem avaliação clínica.'}
];
function toast(message){ $('#toast').textContent=message; $('#toast').classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500); }
function status(message){ $('.local-status').innerHTML=`<span></span>${esc(message)}`; }
function header(title,subtitle,button='',label=''){return `<div class="page-heading"><div><div class="eyebrow">${label||'RITMO PESSOAL'}</div><h1>${title}</h1><p class="subtitle">${subtitle}</p></div>${button}</div>`;}
function btn(action,text,ico='plus',data='',cls='primary'){return `<button class="btn ${cls}" data-action="${action}" ${data}>${icon(ico)}${text}</button>`;}
function empty(text,detail=''){return `<div class="empty"><strong>${text}</strong>${detail}</div>`;}
function taskRows(tasks){return tasks.map(t=>`<div class="task-row ${t.done?'completed':''}"><button class="check ${t.done?'done':''}" data-action="toggle-task" data-id="${t.id}" aria-label="${t.done?'Reabrir':'Concluir'} ${esc(t.title)}" aria-pressed="${t.done}">${t.done?icon('check'):''}</button><div class="task-info"><strong>${esc(t.title)}</strong><small>${esc(t.category)} · ${fmtDate(t.date)}</small></div><span class="tag ${t.priority}">${({alta:'Alta prioridade',media:'Média',baixa:'Baixa'})[t.priority]}</span><div class="row-actions"><button class="icon-button" data-action="edit-task" data-id="${t.id}" aria-label="Editar ${esc(t.title)}">${icon('edit')}</button><button class="icon-button" data-action="delete" data-kind="tasks" data-id="${t.id}" aria-label="Excluir ${esc(t.title)}">${icon('trash')}</button></div></div>`).join('');}
function waterCard(){const count=state.water[today()]||0;return `<section class="card water-card"><div class="card-heading"><h2>Uma pausa para beber água</h2>${icon('water')}</div><div class="water-count">${(count*.25).toLocaleString('pt-BR')} <span>/ ${(state.waterGoal*.25).toLocaleString('pt-BR')} L · meta pessoal</span></div><div class="water-bottom"><div class="water-glasses" aria-label="${count} copos registrados">${Array.from({length:Math.min(state.waterGoal,10)},(_,i)=>icon('glass',i<count?'filled':'')).join('')}</div><div class="water-controls"><button class="icon-button" data-action="water" data-delta="-1" aria-label="Remover um copo" ${count===0?'disabled':''}>${icon('minus')}</button><button class="icon-button" data-action="water" data-delta="1" aria-label="Adicionar um copo de 250 ml">${icon('plus')}</button></div></div><p class="hint" style="margin-top:12px">Cada copo representa 250 ml.</p></section>`;}
function articleCards(list){return list.map((a,i)=>`<article class="article-card ${i===0?'featured':''}"><span class="category">${a.category}</span><h3><button class="article-title" data-action="article" data-id="${a.id}">${a.title}</button></h3><p>${a.summary}</p><div class="article-meta"><span class="source">${a.source}</span><span>${a.lang}</span></div></article>`).join('');}
function dashboard(){
 const tasks=state.tasks.filter(t=>t.date===today()),done=tasks.filter(t=>t.done).length;
 const events=state.events.filter(e=>e.date===selectedDay).sort((a,b)=>a.start.localeCompare(b.start));
 const habitsDone=state.habits.filter(h=>h.days.includes(today())).length;
 return `<section class="daily-hero"><div><div class="eyebrow"><span class="live-dot"></span>${fmtDate(today(),{weekday:'long',day:'numeric',month:'long'})}</div><h1 class="hero-title">Hoje<span class="accent">.</span><span class="hero-subtitle">No seu ritmo.</span></h1></div><div class="hero-side"><p>${state.name?'Olá, '+esc(state.name)+'.<br>':''}${tasks.length-done?'Você tem <strong>'+String(tasks.length-done).padStart(2,'0')+' tarefas</strong><br>para hoje.':'Espaço livre para<br>o seu próximo passo.'}</p><button class="round-action" data-action="new-task" aria-label="Nova tarefa">${icon('plus')}<span>Nova tarefa</span></button></div></section>
 <div class="today-layout section-reveal"><section class="today-tasks"><div class="section-heading"><h2><span class="section-index">01</span> Seu foco</h2><span class="section-meta">${done} / ${tasks.length} concluídas</span></div><div class="day-task-list">${tasks.length?taskRows(tasks.slice(0,6)):empty('O que merece a sua atenção?','Adicione sua primeira tarefa do dia.')}</div><div class="section-bottom"><button class="text-link" data-action="new-task">${icon('plus')}Adicionar tarefa</button><a class="text-link" href="#tarefas">Todas as tarefas <span class="link-mark">↗</span></a></div></section>
 <section class="today-agenda"><div class="section-heading"><h2><span class="section-index">02</span> Sua agenda</h2><a class="text-link" href="#agenda" aria-label="Abrir agenda">${icon('calendar')}</a></div><div class="mini-week">${Array.from({length:7},(_,i)=>{const d=shift(startWeek(new Date()),i),key=dateKey(d);return `<button class="day-button ${key===selectedDay?'active':''}" data-action="select-day" data-date="${key}" aria-label="${fmtDate(key,{weekday:'long',day:'numeric',month:'long'})}" aria-pressed="${key===selectedDay}"><small>${['S','T','Q','Q','S','S','D'][i]}</small><strong>${d.getDate()}</strong></button>`;}).join('')}</div>${events.map(e=>`<button class="timeline-item event-button" data-action="edit-event" data-id="${e.id}"><span class="time-label">${e.start}</span><span class="event-detail ${e.color}"><strong>${esc(e.title)}</strong><small>${e.start} — ${e.end}</small></span></button>`).join('')||empty('Nenhum compromisso','Um espaço para o que surgir.')}<button class="text-link agenda-add" data-action="new-event" data-date="${selectedDay}">${icon('plus')}Reservar um horário</button></section></div>
 <section class="habits-strip section-reveal"><div class="section-heading"><h2><span class="section-index">03</span> Um pouco, todo dia</h2><a href="#habitos" class="text-link">${habitsDone} de ${state.habits.length} hábitos <span class="link-mark">↗</span></a></div><div class="daily-habits">${state.habits.slice(0,3).map((h,i)=>`<button class="daily-habit ${h.days.includes(today())?'is-done':''}" data-action="toggle-habit" data-id="${h.id}" aria-pressed="${h.days.includes(today())}"><span class="habit-number">0${i+1}</span><span class="habit-copy"><strong>${esc(h.title)}</strong><small>${esc(h.goal)}</small></span><span class="check ${h.days.includes(today())?'done':''}">${icon(h.days.includes(today())?'check':'plus')}</span></button>`).join('')||`<button class="add-inline" data-action="new-habit">${icon('plus')}Criar meu primeiro hábito</button>`}</div></section>
 <div class="pause-strip section-reveal"><div><span class="section-index">LEMBRETE GENTIL</span><h2>Já fez uma pausa?</h2></div><div class="pause-water"><span>${((state.water[today()]||0)*.25).toLocaleString('pt-BR')} <small>/ ${(state.waterGoal*.25).toLocaleString('pt-BR')} L</small></span><div><button class="icon-button" data-action="water" data-delta="-1" aria-label="Remover um copo de água" ${(state.water[today()]||0)===0?'disabled':''}>${icon('minus')}</button><button class="btn" data-action="water" data-delta="1">${icon('plus')}250 ml de água</button></div></div></div>
 <section class="learning section-reveal"><div class="section-heading"><h2><span class="section-index">04</span> Fora da lista</h2><a href="#conteudos" class="text-link">Todos os conteúdos <span class="link-mark">↗</span></a></div><div class="articles">${articleCards(articles.slice(0,3))}</div></section>`;
}
function tasksPage(){let tasks=state.tasks.filter(t=>(taskFilter==='todas'||(taskFilter==='pendentes'&&!t.done)||(taskFilter==='concluidas'&&t.done)||(taskFilter==='hoje'&&t.date===today()))&&t.title.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));tasks.sort((a,b)=>Number(a.done)-Number(b.done)||a.date.localeCompare(b.date));return `${header('Uma coisa<br>de cada vez.','Suas tarefas, na ordem que faz sentido para você.',btn('new-task','Nova tarefa'),'MINHAS TAREFAS')}<div class="toolbar"><div class="filters">${[['todas','Todas'],['hoje','Hoje'],['pendentes','Pendentes'],['concluidas','Concluídas']].map(([k,n])=>`<button class="filter ${taskFilter===k?'active':''}" data-action="filter-task" data-filter="${k}" aria-pressed="${taskFilter===k}">${n}</button>`).join('')}</div><input class="search" id="task-search" type="search" placeholder="Buscar uma tarefa…" value="${esc(search)}" aria-label="Buscar tarefas"></div><section class="card wide-tasks" id="task-list">${tasks.length?taskRows(tasks):empty('Nenhuma tarefa por aqui','Crie uma tarefa ou ajuste os filtros.')}</section>`;}
function calendarPage(){const base=calendarView==='mes'?startWeek(new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1)):startWeek(calendarDate);return `${header('Seu tempo.','Compromissos, pausas e espaço entre eles.',btn('new-event','Novo evento'),'AGENDA')}<div class="toolbar"><div class="calendar-toolbar"><h2>${calendarDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h2><button class="icon-button" data-action="calendar-nav" data-delta="-1" aria-label="Período anterior">${icon('left')}</button><button class="icon-button" data-action="calendar-nav" data-delta="1" aria-label="Próximo período">${icon('right')}</button><button class="btn" data-action="calendar-today">Hoje</button></div><div class="filters">${[['mes','Mês'],['semana','Semana']].map(([k,n])=>`<button class="filter ${calendarView===k?'active':''}" data-action="calendar-view" data-view="${k}" aria-pressed="${calendarView===k}">${n}</button>`).join('')}</div></div><section class="card calendar"><div class="calendar-head ${calendarView==='semana'?'week-head':''}">${['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'].map(d=>`<div>${d}</div>`).join('')}</div><div class="${calendarView==='mes'?'month-grid':'week-grid'}">${Array.from({length:calendarView==='mes'?42:7},(_,i)=>{const d=shift(base,i),key=dateKey(d),events=state.events.filter(e=>e.date===key).sort((a,b)=>a.start.localeCompare(b.start));return `<div class="${calendarView==='mes'?'calendar-cell':'week-day'} ${d.getMonth()!==calendarDate.getMonth()?'muted':''}">${calendarView==='semana'?`<span class="week-date">${fmtDate(key,{weekday:'short',day:'numeric'})}</span>`:''}<button class="date-number ${key===today()?'today':''}" data-action="new-event" data-date="${key}" aria-label="Criar evento em ${fmtDate(key,{day:'numeric',month:'long',year:'numeric'})}">${d.getDate()}</button>${events.map(e=>`<button class="calendar-event ${e.color}" data-action="edit-event" data-id="${e.id}" title="${esc(e.title)} · ${e.start}–${e.end}"><b>${e.start}</b> ${esc(e.title)}</button>`).join('')}</div>`;}).join('')}</div></section><p class="notice">Selecione um dia para criar um evento ou um compromisso para editá-lo. Agenda própria, sem conexão com o Google Calendar.</p>`;}
function streak(h){let d=new Date(), count=0;if(!h.days.includes(dateKey(d)))d=shift(d,-1);while(h.days.includes(dateKey(d))){count++;d=shift(d,-1);}return count;}
function habitsPage(){return `${header('Repita o<br>que faz bem.','Acompanhe os hábitos que você escolheu cultivar.',btn('new-habit','Novo hábito'),'HÁBITOS')}<div class="habit-grid">${state.habits.map(h=>`<section class="card habit-card"><div class="card-heading"><span class="habit-symbol">${icon(h.icon)}</span><div><button class="icon-button" data-action="edit-habit" data-id="${h.id}" aria-label="Editar ${esc(h.title)}">${icon('edit')}</button><button class="icon-button" data-action="delete" data-kind="habits" data-id="${h.id}" aria-label="Excluir ${esc(h.title)}">${icon('trash')}</button></div></div><h3>${esc(h.title)}</h3><p>${esc(h.goal)}</p><div class="habit-week">${Array.from({length:7},(_,i)=>{const d=shift(new Date(),i-6),key=dateKey(d);return `<div class="habit-day">${fmtDate(key,{weekday:'short'}).slice(0,3)}<span class="${h.days.includes(key)?'done':''}" title="${fmtDate(key)}">${h.days.includes(key)?icon('check'):d.getDate()}</span></div>`;}).join('')}</div><div class="habit-card-bottom"><small>${streak(h)} dia(s) de sequência</small><button class="btn ${h.days.includes(today())?'':'primary'}" data-action="toggle-habit" data-id="${h.id}">${icon(h.days.includes(today())?'check':'plus')}${h.days.includes(today())?'Feito hoje':'Registrar'}</button></div></section>`).join('')||`<section class="card">${empty('Qual hábito você quer cultivar?','Use “Novo hábito” para começar.')}</section>`}</div>`;}
const mealKinds=['Café da manhã','Almoço','Lanche','Jantar'];
function mealsPage(){const meals=state.meals[mealDate]||{};return `${header('À mesa.','Um lugar para organizar o que você vai comer.','','ALIMENTAÇÃO')}<div class="toolbar"><div class="date-control"><button class="icon-button" data-action="meal-nav" data-delta="-1" aria-label="Dia anterior">${icon('left')}</button><input id="meal-date" type="date" value="${mealDate}" aria-label="Dia do planejamento alimentar"><button class="icon-button" data-action="meal-nav" data-delta="1" aria-label="Próximo dia">${icon('right')}</button><button class="btn" data-action="meal-today">Hoje</button></div><span class="hint">Seu planejamento pessoal</span></div><div class="meal-grid">${mealKinds.map((kind,i)=>`<section class="card meal-card"><div class="card-heading"><h2>${kind}</h2><button class="icon-button" data-action="edit-meal" data-slot="${i}" aria-label="Editar ${kind}">${icon('edit')}</button></div><div class="meal-icon">${icon(i===0?'sun':'food')}<small>${['Para começar o dia','Uma pausa no meio do dia','Entre uma atividade e outra','Para fechar o dia'][i]}</small></div>${meals[i]?`<p class="meal-content">${esc(meals[i])}</p>`:`<button class="add-inline" data-action="edit-meal" data-slot="${i}">${icon('plus')}Planejar refeição</button>`}</section>`).join('')}</div><div class="callout"><strong>Inspiração com uma boa fonte.</strong><p>Consulte o <a href="${articles[0].url}" target="_blank" rel="noopener noreferrer">Guia Alimentar do Ministério da Saúde</a> para conhecer orientações gerais sobre alimentação. Este espaço organiza suas escolhas; não prescreve dietas.</p></div><div style="margin-top:22px">${waterCard()}</div>`;}
function blogPage(){return `${header('Uma boa<br>leitura.','Ideias de quem estuda o assunto. Direto da fonte.','','INSPIRE-SE')}<div class="filters blog-categories">${['Todos','Alimentação','Bem-estar','Organização'].map(c=>`<button class="filter ${c===blogFilter?'active':''}" data-action="filter-blog" data-filter="${c}" aria-pressed="${c===blogFilter}">${c}</button>`).join('')}</div><div class="articles blog-grid">${articleCards(articles.filter(a=>blogFilter==='Todos'||a.category===blogFilter))}</div><p class="notice">Curadoria editorial com resumos próprios e links para os materiais originais. Fontes consultadas em 29/09/2026. Conteúdos informativos, sem atendimento profissional individualizado.</p>`;}
function devicePreferences(){return `<section class="card appearance-panel"><h2>Aparência</h2><p>Escolha a luz que combina com o seu momento.</p><div class="appearance-options" role="group" aria-label="Tema do aplicativo"><button type="button" class="appearance-option" data-theme-choice="system" aria-pressed="false"><span class="theme-swatch system" aria-hidden="true"></span>Sistema</button><button type="button" class="appearance-option" data-theme-choice="light" aria-pressed="false"><span class="theme-swatch light" aria-hidden="true"></span>Claro</button><button type="button" class="appearance-option" data-theme-choice="dark" aria-pressed="false"><span class="theme-swatch dark" aria-hidden="true"></span>Escuro</button></div><p class="hint">A preferência fica salva neste dispositivo. O modo escuro usa fundo grafite e cores suaves.</p></section><section class="card"><h2>Ritmo como aplicativo</h2><p data-install-description>Adicione ao seu computador ou à tela inicial do celular.</p><button type="button" class="btn primary" data-install-app>Instalar aplicativo</button></section>`;}
function settingsPage(){const signed=window.RitmoCloud?.signedIn;return `${header('Do seu jeito.','Sua conta, suas preferências e seus dados.','','MEU ESPAÇO')}<div class="settings-grid"><section class="card"><h2>Como você quer ser chamado?</h2><p>Um nome para deixar este espaço mais seu.</p><form id="profile-form"><label>Seu nome<input name="name" maxlength="40" value="${esc(state.name)}" placeholder="Seu primeiro nome"></label><label>Meta pessoal de água (copos de 250 ml)<input class="inline-number" name="waterGoal" type="number" min="1" max="24" value="${state.waterGoal}" required></label><span class="hint">Ajuste à sua necessidade. A meta não é uma recomendação médica.</span><button class="btn primary" type="submit">Salvar preferências</button></form></section><div class="column"><section class="card"><h2>${signed?'Sua conta':'Leve seu ritmo com você'}</h2><p>${signed?`Conectado como ${esc(window.RitmoCloud.email)}. Alterações são sincronizadas entre seus dispositivos.`:'Entre na sua conta para guardar tarefas, hábitos e planos e acessá-los em outros dispositivos.'}</p>${signed?btn('logout','Sair da conta','close','',''):btn('login','Entrar ou criar conta','cloud')}${signed?btn('sync','Sincronizar agora','cloud','',''):''}${!window.RitmoCloud?.configured?'<p class="hint">A conexão com o Firebase está indisponível. Confira sua internet e recarregue a página.</p>':''}</section><section class="card"><h2>Uma cópia dos seus planos</h2><p>Exporte seus dados em JSON. Você pode restaurar uma cópia quando precisar.</p>${btn('export','Exportar backup','download','','')}${btn('import','Restaurar backup','plus','','')}<input type="file" accept="application/json,.json" id="import-file" hidden></section>${devicePreferences()}</div></div>`;}
function render(animate=false){window.RitmoMotion?.clear();const requested=location.hash.replace('#','')||'inicio';route=[...navs.map(n=>n[0]),'ajustes'].includes(requested)?requested:'inicio';$('#breadcrumb').textContent=navs.find(n=>n[0]===route)?.[2]||'Meu espaço';document.title=`${$('#breadcrumb').textContent} · Ritmo`;$('#navigation').innerHTML=navs.map(([key,ico,name])=>`<a href="#${key}" class="nav-item ${route===key?'active':''}" title="${name}" ${route===key?'aria-current="page"':''}>${icon(ico)}<span>${name}</span></a>`).join('');const pages={inicio:dashboard,tarefas:tasksPage,agenda:calendarPage,habitos:habitsPage,alimentacao:mealsPage,conteudos:blogPage,ajustes:settingsPage};$('#main').innerHTML=pages[route]();window.RitmoMotion?.enter(animate);document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));$('.profile strong').textContent=state.name||'Meu espaço';document.querySelectorAll('.avatar').forEach(el=>el.textContent=(state.name||'V').charAt(0).toUpperCase());$('.profile small').textContent=window.RitmoCloud?.signedIn?'Conta sincronizada':'Demonstração';updateCloudBanner();window.RitmoTheme?.refreshControls();window.RitmoInstall?.refresh();}
function updateCloudBanner(){let el=$('#cloud-banner');if(!el){el=document.createElement('div');el.id='cloud-banner';el.className='cloud-banner';$('.topbar').after(el);}if(window.RitmoCloud?.signedIn){el.hidden=true;}else{el.hidden=false;el.innerHTML=`<span>Demonstração <span class="banner-separator">/</span> Explore à vontade. Entre para salvar seus planos.</span><button data-action="login">Entrar ou criar conta ↗</button>`;status('Modo demonstração');}}
let opener;
let formRevision=0;
function openDialog(title,body){formRevision=revision;opener=document.activeElement;$('#dialog').innerHTML=`<div class="dialog-heading"><h2 id="dialog-title">${title}</h2><button class="icon-button" data-action="close-dialog" aria-label="Fechar">${icon('close')}</button></div>${body}`;if(!$('#dialog').open)$('#dialog').showModal();window.RitmoMotion?.dialog();}
function closeDialog(){if(operationBusy)return;$('#dialog').close();opener?.focus();}
function field(label,name,type='text',value='',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function formEnd(edit=false,kind='',id=''){return `<p class="error" id="form-error" role="alert"></p><div class="form-actions">${edit&&kind==='events'?`<button type="button" class="btn danger" data-action="delete" data-kind="events" data-id="${id}">Excluir</button>`:''}<button type="button" class="btn" data-action="close-dialog">Cancelar</button><button type="submit" class="btn primary">Salvar</button></div></form>`;}
function taskDialog(id){const t=state.tasks.find(t=>t.id===id);openDialog(t?'Editar tarefa':'Um novo passo',`<form id="task-form" data-id="${id||''}">${field('O que você quer fazer?','title','text',t?.title||'','required maxlength="140" autofocus')}<div class="form-grid">${field('Data','date','date',t?.date||today(),'required')}<label>Prioridade<select name="priority">${[['alta','Alta'],['media','Média'],['baixa','Baixa']].map(([v,n])=>`<option value="${v}" ${v===(t?.priority||'media')?'selected':''}>${n}</option>`).join('')}</select></label></div>${field('Área da vida','category','text',t?.category||'Pessoal','required maxlength="40"')}${formEnd()}`);}
function eventDialog(id,date){const e=state.events.find(e=>e.id===id);openDialog(e?'Editar compromisso':'Reserve um momento',`<form id="event-form" data-id="${id||''}">${field('Nome do compromisso','title','text',e?.title||'','required maxlength="140" autofocus')}${field('Data','date','date',e?.date||date||today(),'required')}<div class="form-grid">${field('Começa às','start','time',e?.start||'09:00','required')}${field('Termina às','end','time',e?.end||'10:00','required')}</div><div class="form-grid">${field('Área da vida','category','text',e?.category||'Pessoal','required maxlength="40"')}<label>Cor<select name="color">${[['green','Verde'],['purple','Lilás'],['orange','Laranja']].map(([v,n])=>`<option value="${v}" ${v===e?.color?'selected':''}>${n}</option>`).join('')}</select></label></div><label>Anotações<textarea name="notes" maxlength="1000">${esc(e?.notes||'')}</textarea></label>${formEnd(!!e,'events',id)}`);}
function habitDialog(id){const h=state.habits.find(h=>h.id===id);openDialog(h?'Editar hábito':'Cultive um novo hábito',`<form id="habit-form" data-id="${id||''}">${field('Seu hábito diário','title','text',h?.title||'','required maxlength="100" autofocus')}${field('Um pequeno objetivo','goal','text',h?.goal||'','required maxlength="120"')}<label>Ícone<select name="icon">${[['leaf','Cuidado'],['book','Leitura'],['sun','Bem-estar'],['habit','Movimento']].map(([v,n])=>`<option value="${v}" ${v===h?.icon?'selected':''}>${n}</option>`).join('')}</select></label>${formEnd()}`);}
function mealDialog(slot){openDialog(mealKinds[slot],`<form id="meal-form" data-slot="${slot}"><p class="hint">${fmtDate(mealDate,{day:'numeric',month:'long',year:'numeric'})}</p><label>O que você pretende comer?<textarea name="meal" maxlength="1000" autofocus placeholder="Anote alimentos, preparos ou ideias…">${esc(state.meals[mealDate]?.[slot]||'')}</textarea></label><p class="hint">Deixe vazio para remover este planejamento.</p>${formEnd()}`);}
async function download(data,name){if(window.RitmoDevice?.exportBackup){await window.RitmoDevice.exportBackup(data,name);return;}const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function commit(next){if(operationBusy)throw new Error('Aguarde a alteração atual terminar.');validateState(next);operationBusy=true;try{if(window.RitmoCloud?.signedIn){if(!loaded)throw new Error('Sincronize sua conta antes de alterar os dados.');status('Salvando…');try{const result=await window.RitmoCloud.save(next,$('#dialog').open?formRevision:revision);revision=result.revision;status('Sincronizado');}catch(err){status('Alteração não salva');if(err.conflict){await download({exportedAt:new Date().toISOString(),data:next},`ritmo-alteracao-pendente-${today()}.json`);toast('Outro dispositivo alterou seus dados. Uma cópia da sua tentativa foi exportada.');await sync(true);formRevision=revision;}throw err;}}state=next;render();}finally{operationBusy=false;}}
async function change(fn){const next=structuredClone(state);fn(next);await commit(next);}
async function sync(force=false){if(syncBusy||(!force&&operationBusy)||!window.RitmoCloud?.signedIn)return;syncBusy=true;const account=window.RitmoCloud.userId;try{status('Sincronizando…');const result=await window.RitmoCloud.load();if(window.RitmoCloud.userId!==account)return;const next=result?.data||emptyState();validateState(next);if(!loaded||revision!==(result?.revision||0)){state=next;revision=result?.revision||0;render();}loaded=true;status(window.RitmoCloud.connected?'Sincronizado':'Sem conexão');}catch(err){status('Sem sincronização');if(force)throw err;}finally{syncBusy=false;}}
function loginDialog(signup=false){if(!window.RitmoCloud?.configured){openDialog('Conecte sua conta',`<p class="section-intro">Não foi possível carregar a conexão com o Firebase.</p><p class="hint">Verifique sua conexão com a internet e recarregue esta página usando a prévia local ou o endereço publicado. O guia README também explica a ativação do login e das regras do banco.</p><div class="form-actions"><button class="btn primary" data-action="close-dialog">Explorar a demonstração</button></div>`);return;}openDialog(signup?'Seu primeiro passo':'Bem-vindo ao seu espaço',`<form id="auth-form" data-mode="${signup?'signup':'login'}">${field('E-mail','email','email','','required autocomplete="email" autofocus')}${field('Senha','password','password','','required minlength="8" maxlength="128" autocomplete="'+(signup?'new-password':'current-password')+'"')}<p class="error" id="form-error" role="alert"></p><button class="btn primary" type="submit">${signup?'Criar minha conta':'Entrar'}</button><button type="button" class="text-link" data-action="${signup?'login':'signup'}">${signup?'Já tenho uma conta':'Ainda não tenho uma conta'}</button>${!signup?'<button type="button" class="text-link" data-action="forgot-password">Esqueci minha senha</button>':''}</form>`);}
function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(parseDate(s).valueOf())&&dateKey(parseDate(s))===s;}
function validateState(s){const str=(v,n=150)=>typeof v==='string'&&v.length<=n;const id=v=>typeof v==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(v);const fail=()=>{throw new Error('Os dados não estão no formato de backup do Ritmo.');};if(!s||s.schemaVersion!==1||!str(s.name,40)||!Number.isInteger(s.waterGoal)||s.waterGoal<1||s.waterGoal>24)fail();for(const key of ['tasks','events','habits']){if(!Array.isArray(s[key])||s[key].length>5000||new Set(s[key].map(x=>x?.id)).size!==s[key].length)fail();}for(const t of s.tasks)if(!t||!id(t.id)||!str(t.title,140)||!t.title.trim()||!validDate(t.date)||!['alta','media','baixa'].includes(t.priority)||!str(t.category,40)||typeof t.done!=='boolean')fail();for(const e of s.events)if(!e||!id(e.id)||!str(e.title,140)||!e.title.trim()||!validDate(e.date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(e.start)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(e.end)||e.end<=e.start||!['green','purple','orange'].includes(e.color)||!str(e.category,40)||!str(e.notes,1000))fail();for(const h of s.habits)if(!h||!id(h.id)||!str(h.title,100)||!h.title.trim()||!str(h.goal,120)||!['leaf','book','sun','habit'].includes(h.icon)||!Array.isArray(h.days)||h.days.length>20000||!h.days.every(validDate))fail();for(const key of ['water','meals'])if(!s[key]||typeof s[key]!=='object'||Array.isArray(s[key]))fail();for(const [date,value] of Object.entries(s.water))if(!validDate(date)||!Number.isInteger(value)||value<0||value>100)fail();for(const [date,value] of Object.entries(s.meals)){if(!validDate(date)||!value||typeof value!=='object'||Array.isArray(value))fail();for(const [slot,meal] of Object.entries(value))if(!['0','1','2','3'].includes(slot)||!str(meal,1000))fail();}if(JSON.stringify(s).length>2000000)fail();return s;}
document.addEventListener('click',async e=>{if(e.target.closest('a.skip')){e.preventDefault();document.querySelector('#main').focus();return;}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;try{switch(a){
case 'settings':location.hash='ajustes';break;
case 'new-task':taskDialog();break;case 'edit-task':taskDialog(id);break;
case 'toggle-task':await change(s=>{const t=s.tasks.find(x=>x.id===id);t.done=!t.done;});break;
case 'filter-task':taskFilter=b.dataset.filter;render();break;
case 'new-event':eventDialog(null,b.dataset.date);break;case 'edit-event':eventDialog(id);break;
case 'calendar-nav':if(calendarView==='mes')calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+Number(b.dataset.delta),1);else calendarDate=shift(calendarDate,Number(b.dataset.delta)*7);render();break;
case 'calendar-today':calendarDate=new Date();render();break;case 'calendar-view':calendarView=b.dataset.view;render();break;
case 'select-day':selectedDay=b.dataset.date;render();break;
case 'new-habit':habitDialog();break;case 'edit-habit':habitDialog(id);break;
case 'toggle-habit':await change(s=>{const h=s.habits.find(x=>x.id===id);h.days=h.days.includes(today())?h.days.filter(d=>d!==today()):[...h.days,today()];});break;
case 'water':await change(s=>s.water[today()]=Math.min(100,Math.max(0,(s.water[today()]||0)+Number(b.dataset.delta))));break;
case 'edit-meal':mealDialog(b.dataset.slot);break;case 'meal-nav':mealDate=dateKey(shift(parseDate(mealDate),Number(b.dataset.delta)));render();break;case 'meal-today':mealDate=today();render();break;
case 'filter-blog':blogFilter=b.dataset.filter;render();break;
case 'article':{const article=articles.find(x=>x.id===Number(id));openDialog(article.title,`<span class="tag">${article.category}</span><div class="article-body">${article.body.split('\n\n').map(p=>`<p>${p}</p>`).join('')}</div><p class="hint">Resumo editorial do Ritmo · Fonte: ${article.source}</p><div class="form-actions"><a class="btn primary" href="${article.url}" target="_blank" rel="noopener noreferrer">Ler na fonte original</a></div>`);break;}
case 'delete':openDialog('Excluir este item?',`<p class="section-intro">Esta ação remove o item e seu histórico. Deseja continuar?</p><div class="form-actions"><button class="btn" data-action="close-dialog">Cancelar</button><button class="btn danger" data-action="confirm-delete" data-kind="${b.dataset.kind}" data-id="${id}">Excluir item</button></div>`);break;
case 'confirm-delete':await change(s=>s[b.dataset.kind]=s[b.dataset.kind].filter(x=>x.id!==id));closeDialog();toast('Item excluído.');break;
case 'close-dialog':closeDialog();break;
case 'export':await download({exportedAt:new Date().toISOString(),data:state},`ritmo-backup-${today()}.json`);toast('Backup exportado.');break;
case 'import':$('#import-file').click();break;
case 'confirm-import':await commit(importCandidate);importCandidate=null;closeDialog();toast('Backup restaurado.');break;
case 'login':loginDialog();break;case 'signup':loginDialog(true);break;
case 'forgot-password':openDialog('Recuperar acesso',`<form id="forgot-form">${field('Seu e-mail','email','email','','required autocomplete="email" autofocus')}${formEnd()}</form>`);break;
case 'logout':if(operationBusy)throw new Error('Aguarde o salvamento antes de sair.');await window.RitmoCloud.logout();loaded=false;revision=0;state=demoState();render();toast('Você saiu da conta.');break;
case 'sync':await sync(true);toast('Seus dados estão atualizados.');break;
}}catch(err){toast(err.message||'Não foi possível concluir. Tente novamente.');}});
document.addEventListener('input',e=>{if(e.target.id==='task-search'){search=e.target.value;const fragment=document.createElement('div');fragment.innerHTML=tasksPage();$('#task-list').innerHTML=fragment.querySelector('#task-list').innerHTML;}});
let importCandidate=null;
document.addEventListener('change',async e=>{if(e.target.id==='meal-date'&&validDate(e.target.value)){mealDate=e.target.value;render();}if(e.target.id==='import-file'&&e.target.files[0]){try{const file=e.target.files[0];if(file.size>2000000)throw new Error('O backup deve ter até 2 MB.');const parsed=JSON.parse(await file.text());importCandidate=validateState(parsed.data);openDialog('Restaurar este backup?',`<p class="section-intro">O backup contém ${importCandidate.tasks.length} tarefas, ${importCandidate.events.length} eventos e ${importCandidate.habits.length} hábitos. Ele substituirá os dados atuais${window.RitmoCloud?.signedIn?' da sua conta':''}.</p><div class="form-actions"><button class="btn" data-action="close-dialog">Cancelar</button><button class="btn primary" data-action="confirm-import">Restaurar dados</button></div>`);}catch(err){toast(err.message||'Arquivo inválido.');}e.target.value='';}});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,id=f.dataset.id,data=Object.fromEntries(new FormData(f)),submit=f.querySelector('[type="submit"]');if(submit.disabled)return;submit.disabled=true;try{if(f.id==='task-form'){data.title=data.title.trim();data.category=data.category.trim();await change(s=>{const item=s.tasks.find(x=>x.id===id);if(item)Object.assign(item,data);else s.tasks.push({...data,id:uid(),done:false});});}
else if(f.id==='event-form'){if(data.end<=data.start)throw new Error('O término deve ser depois do início, no mesmo dia.');data.title=data.title.trim();await change(s=>{const item=s.events.find(x=>x.id===id);if(item)Object.assign(item,data);else s.events.push({...data,id:uid()});});}
else if(f.id==='habit-form'){data.title=data.title.trim();await change(s=>{const item=s.habits.find(x=>x.id===id);if(item)Object.assign(item,data);else s.habits.push({...data,id:uid(),days:[]});});}
else if(f.id==='meal-form'){await change(s=>{s.meals[mealDate]??={};if(data.meal.trim())s.meals[mealDate][f.dataset.slot]=data.meal.trim();else delete s.meals[mealDate][f.dataset.slot];});}
else if(f.id==='profile-form'){await change(s=>{s.name=data.name.trim();s.waterGoal=Number(data.waterGoal);});toast('Preferências salvas.');return;}
else if(f.id==='auth-form'){if(f.dataset.mode==='signup'){const result=await window.RitmoCloud.signup(data.email,data.password);if(!result){closeDialog();toast('Confira seu e-mail para confirmar a conta. Depois, entre aqui.');return;}}else await window.RitmoCloud.login(data.email,data.password);state=emptyState();loaded=false;revision=0;render();await sync(true);}
else if(f.id==='forgot-form'){await window.RitmoCloud.recover(data.email);closeDialog();toast('Se o e-mail estiver cadastrado, você receberá um link de recuperação.');return;}
else return;closeDialog();toast(window.RitmoCloud?.signedIn?'Salvo na sua conta.':'Atualizado na demonstração.');}catch(err){const error=f.querySelector('#form-error');if(error)error.textContent=err.message;else toast(err.message);}finally{submit.disabled=false;}});
$('#dialog').addEventListener('cancel',e=>{if(operationBusy)e.preventDefault();});
window.addEventListener('hashchange',()=>{render(true);window.scrollTo({top:0,behavior:'instant'});});
window.addEventListener('focus',()=>sync());
window.addEventListener('ritmo-remote-change',()=>{
 if(operationBusy||syncBusy||!loaded||!window.RitmoCloud?.signedIn)return;
 const remote=window.RitmoCloud.latest;
 if(remote&&remote.revision!==revision){try{validateState(remote.data);state=remote.data;revision=remote.revision;render();status('Sincronizado');}catch{status('Dados inválidos na nuvem');}}
});
window.addEventListener('ritmo-sync-error',()=>{status('Sincronização indisponível');toast(window.RitmoCloud?.listenerError?.message||'Não foi possível sincronizar.');});
window.addEventListener('ritmo-connection',()=>{if(window.RitmoCloud?.signedIn){if(!window.RitmoCloud.connected)status('Sem conexão');else sync();}});

let lastToday=today();setInterval(()=>{if(document.hidden)return;if(lastToday!==today()){lastToday=today();selectedDay=today();mealDate=today();render();}sync();},15000);
render(true);
window.RitmoApp={validateState,emptyState,closeDialog};
window.addEventListener('ritmo-cloud-ready',async()=>{try{if(window.RitmoCloud?.signedIn){state=emptyState();loaded=false;revision=0;render();await sync(true);}else{loaded=false;revision=0;state=demoState();render();}}catch(err){render();toast(err.message);}});
})();

